import NextTopLoader from "nextjs-toploader";
import { Inter } from "next/font/google";
import "./globals.css";
import PlainLayout from '@/component/master/PlainLayout';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

       <PlainLayout>

       {children}
       <NextTopLoader color="#E60000" speed={200} height={2}/>


       </PlainLayout>

      </body>
    </html>
  );
}
